using System.Text.Json.Serialization;

namespace ChattyMcChatface.Core.Dtos;

/// <summary>
/// Represents the expected structured JSON response from AI providers.
/// </summary>
public class AiStructuredResponseDto
{
    /// <summary>
    /// The name of the AI persona generating the response.
    /// </summary>
    [JsonPropertyName("ai_persona")]
    public string? AiPersona { get; set; }

    /// <summary>
    /// The type or category of the response (e.g., "Reflective Inquiry", "Sarcastic Quip").
    /// </summary>
    [JsonPropertyName("response_type")]
    public string? ResponseType { get; set; }

    /// <summary>
    /// The actual message content generated by the AI.
    /// </summary>
    [JsonPropertyName("message")]
    public string? Message { get; set; }
}